"""Regenerate docs/ references from docs/register_catalogue.json."""

import json
from pathlib import Path


DIRECTORY = Path(__file__).resolve().parent / "docs"
REGISTER_COLUMNS = (
    ("name", "Register"), ("source", "Source"), ("description", "Description"),
    ("units", "Units"), ("known_width", "Known width"),
    ("allowed_values", "Allowed values"), ("example", "Example"),
    ("validation", "Validation / interpretation"), ("status", "Status"),
)
LUT_COLUMNS = (
    ("word", "Word"), ("bits_31_24", "31:24"), ("bits_23_16", "23:16"),
    ("bits_15_8", "15:8"), ("bits_7_0", "7:0"),
)


def _table(rows, columns):
    lines = ["| " + " | ".join(label for _, label in columns) + " |"]
    lines.append("| " + " | ".join("---" for _ in columns) + " |")
    for row in rows:
        values = [str(row[key]).replace("|", "\\|").replace("\n", "<br>") for key, _ in columns]
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def render_markdown(catalogue):
    sections = [
        f"# {catalogue['title']}",
        "Generated from `register_catalogue.json`; edit the catalogue and run "
        "`python -m C55.generate_register_reference`. Do not edit this file or the workbook manually.",
        "## Registers", _table(catalogue["registers"], REGISTER_COLUMNS),
        "## Scalar coefficient LUT (documentation only)",
        "The supplied table describes 16 sets, 32 phases per set, and seven coefficient "
        "bytes in two 32-bit words per phase. Byte ordering below is bit placement, "
        "not a specification of memory endianness.",
        _table(catalogue["lut"], LUT_COLUMNS),
        "## Contract and source notes",
    ]
    for note in catalogue["notes"]:
        sections.extend([f"### {note['topic']}", note["text"]])
    return "\n\n".join(sections) + "\n"


def write_workbook(catalogue, path):
    # Documentation-only dependency; never imported by the resampler.
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    workbook = Workbook()
    workbook.remove(workbook.active)
    tables = (
        ("Registers", catalogue["registers"], REGISTER_COLUMNS),
        ("LUT layout", catalogue["lut"], LUT_COLUMNS),
        ("Notes", catalogue["notes"], (("topic", "Topic"), ("text", "Description"))),
    )
    for title, rows, columns in tables:
        sheet = workbook.create_sheet(title)
        sheet.append([label for _, label in columns])
        for row in rows:
            sheet.append([row[key] for key, _ in columns])
        sheet.freeze_panes = "A2"
        sheet.auto_filter.ref = sheet.dimensions
        for cell in sheet[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill("solid", fgColor="166678")
        for row in sheet:
            for cell in row:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
        for index, (key, _) in enumerate(columns, 1):
            width = 30
            if key in ("description", "validation", "allowed_values"):
                width = 55
            if key == "text":
                width = 110
            sheet.column_dimensions[get_column_letter(index)].width = width
        for index in range(2, sheet.max_row + 1):
            sheet.row_dimensions[index].height = 100
    workbook.properties.title = catalogue["title"]
    workbook.properties.description = "Generated from C55/docs/register_catalogue.json; do not edit manually."
    workbook.save(path)


def main():
    catalogue = json.loads((DIRECTORY / "register_catalogue.json").read_text(encoding="utf-8"))
    write_workbook(catalogue, DIRECTORY / "registers.xlsx")
    (DIRECTORY / "registers.md").write_text(render_markdown(catalogue), encoding="utf-8")


if __name__ == "__main__":
    main()
